# Change these first
owner: elfoche # Your GitHub organization or username, where this repository lives
repo: monitoreo # The name of this repository

sites:
  - name: UNER - Web
    url: https://uner.edu.ar
  - name: UNER - Campus
    url: https://campus.uner.edu.ar
  - name: UNER - Diaguita
    url: https://diaguita.uner.edu.ar
  - name: UNER - Guaraní
    url: https://g3autogestion.uner.edu.ar/g3w3/
  - name: UNER - Comdoc
    url: http://jboss.comdoc.uner.edu.ar/comdocII/webtier/Signin
  - name: UNER - GitLab
    url: https://gitlab.uner.edu.ar/users/sign_in
  - name: UNER - DDJJ
    url: https://autogestion.uner.edu.ar/
  - name: UNER - Turnero
    url: https://turnosfirmadigital.uner.edu.ar/nuevo-turno 
  - name: UNER - Redmine
    url: https://redmine.uner.edu.ar/ 
  - name: UNER - Jitsi
    url: https://jitsi.uner.edu.ar/    
  - name: UADER - Web
    url: https://fcytcdelu.uader.edu.ar/
  - name: UADER - Campus
    url: https://campus.fcytcdelu.uader.edu.ar/
  - name: UADER - Guaraní
    url: http://guarani3w.uader.edu.ar/gestion/  
  - name: UCU - Web
    url: https://ucu.edu.ar
  - name: UCU - Campus
    url: https://moodle.ucu.edu.ar/
  - name: UCU - SAO
    url: https://alumnos.ucu.edu.ar/
  - name: UCU - SIG
    url: http://administracion.ucu.edu.ar/
  - name: UCU - Koha
    url: http://biblioteca.ucu.edu.ar/
  - name: UCU - Maraton
    url: https://maraton.ucu.edu.ar/  
  - name: MCU - Web
    url: https://cdeluruguay.gob.ar/
  - name: MCU - GTH
    url: http://produccion.cdeluruguay.gob.ar/GTH/forms/login.jsp
  - name: MCU - GAF
    url: http://produccion.cdeluruguay.gob.ar/GAF/forms/login.jsp    
  - name: MCU - GRH
    url: http://produccion.cdeluruguay.gob.ar/GRH/forms/login.jsp
  - name: MCU - GAT
    url: http://produccion.cdeluruguay.gob.ar/GAT/forms/login.jsp
  - name: MCU - GTH
    url: http://produccion.cdeluruguay.gob.ar/GTH/forms/login.jsp
  - name: MCU - STS
    url: http://produccion.cdeluruguay.gob.ar/STS/forms/login.jsp
  - name: MCU - Owncloud
    url: https://cloud.cdeluruguay.gob.ar/login?redirect_url=/apps/dashboard/
  - name: MCU - Proyectos
    url: http://proyectos.cdeluruguay.gob.ar/login?back_url=http%3A%2F%2Fproyectos.cdeluruguay.gob.ar%2F
  - name: MCU - GitLab
    url: https://git.cdeluruguay.gob.ar/users/sign_in
  - name: Google AR
    url: https://www.google.com.ar

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /monitoreo
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitoreo
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
